### ISSUE TITLE
Planning to move my project here!

### ISSUE THREAD

**Issue by vigo** [jazzband/roadies#145]
Hi, I'm the author and maintainer of https://github.com/vigo/django2-project-template I'd like to move my project here... What do you think about it? Thanks

**Comment by jezdez** [comment]
Hi @vigo! Thanks for your question, I'm impressed by the project template. But I'm afraid this isn't quite a good fit for Jazzband since Django project templates are highly selective and too subjective for general use.

I know this may not be satisfying and the template is certainly complex, but in its entirety it's more a collection of snippets and I think this would have a smaller chance for a successful maintenance via the Jazzband members than other more library-like packages. I hope you understand.

**Comment by vigo** [comment]
After I inspect other projects, I was thinking about the same as you... Sure no problem, love to be the part of the group :)
