### ISSUE TITLE
Secret code for django-push-notifications

### ISSUE THREAD

**Issue by odinuge** [jazzband/roadies#148]
Hi roadie(s),

I need a secret key for django-push-notification for https://github.com/jazzband/django-push-notifications/pull/505, so that we can release v2.0.0 https://github.com/jazzband/django-push-notifications/pull/502 of the project 🎉

**Comment by jezdez** [comment]
Hm, so setting up PyPI implies that there is a project lead (or the roadies as a fallback). Since I'm the only roadie right now and not familiar with the project I'd like to ask you to figure out who could be the person willing to review releases when they happen.

@jleclanche is the developer with the most contributions to the project. Maybe they could stand in as project lead to review releases done by other members?

**Comment by jleclanche** [comment]
I'm happy to help if I can but although I authored django-push-notifications, I've not contributed to it in a long time.

**Comment by odinuge** [comment]
Thanks for the answer @jezdez!

It would be perfect if you @jleclanche could do that! I don't know enough about the project and the code to take such a role, so I think @jleclanche is the perfect man!

The project desperately need a new release(s) now, both to add support for python 3.7 (https://github.com/jazzband/django-push-notifications/pull/502) and the problems with the version of apns2 (https://github.com/jazzband/django-push-notifications/pull/516). Since we have breaking changes, I think `v2.0.0` is the natural new release.

I think we should cherry-pick the two PRs I mentioned into a new release, `v1.6.1`.

As long as new features or bug fixes are merged to master, I think we should release new patch version more often. We now have changes that has been in master for more than 18 months, still without being part in a release.

Hopefully we can release a new version as soon as possible, most importantly the `v1.6.1`! :smile:

**Comment by jezdez** [comment]
@jleclanche @odinuge Excellent, I'll set up the release process and add @jleclanche as project lead.

In practice the releasing will happen semi-automatic. @jleclanche will get an email as soon a release has been made to the Jazzband Package Index vom Travis to confirm the release via the Website and the press of a button before it's shipped to PyPI. Please make sure to review the changes going out before confirming to assure a secure payload.

**Comment by jezdez** [comment]
@odinuge About that 1.6.1 release, I'm afraid since we've already made significant progress in the repo towards a 2.0.0 and the travis config needing updates to facilitate I'll need to create a 1.6.x branch to do that. From there we can cut the tag and do the 1.6.1 release. Then merge the 1.6.x branch into master and do a 2.0.0 release.

**Comment by jezdez** [comment]
Wait, now I'm confused master is already marked as becoming 2.0.0, but https://github.com/jazzband/django-push-notifications/pull/516 is supposed to be the base for 1.6.1?

@odinuge Could you please let me know what the last commit of a 1.6.x release was that you want to cherry-pick to create 1.6.1? Why open PRs against master?

**Comment by jezdez** [comment]
@odinuge Would https://github.com/jazzband/django-push-notifications/tree/1.6.0 be the base for 1.6.1?

**Comment by odinuge** [comment]
You are correct! The tag `1.6.0` will then be the base for `1.6.1`, with this diff from current master: https://github.com/jazzband/django-push-notifications/compare/1.6.0...master (the PR with the changelog and bump in setup.py to "2.0.0", aka. the next version, was merged before everything was good to go, but it shouldn't matter).

There are already some breaking changes in master, making it impossible to release as `1.6.1`. We should also consider if we want to drop support for python 3.4 when we will release a new major version with `2.0.0`.

**Comment by jezdez** [comment]
Let's just release 1.6.1 with the dependency update in https://github.com/jazzband/django-push-notifications/pull/516, not the full-blown backwards-incompatible changes.

**Comment by odinuge** [comment]
Perfect! Should we cherry-pick support for python v3.7 too? https://github.com/jazzband/django-push-notifications/pull/502

**Comment by odinuge** [comment]
Also, not sure if I understand why we need to merge the release branch `v1.6.x` into master. :thinking: When the release in the branch is ready for release, we create the release and a corresponding git tag.

**Comment by jezdez** [comment]
> Also, not sure if I understand why we need to merge the release branch `v1.6.x` into master. 🤔 When the release in the branch is ready for release, we create the release and a corresponding git tag.

Because the release branch needs to have the changes to do the semi-automatic releases as well. It's also a good practice to not keep releases branches open-ended to not accidentally forget commits that were done in them. Practically speaking, everything in 1.6.1 is okay to have in 2.0.0 and the release branch is just a temporary side-stepping while we clean up the repo for a double-release.  think we should delete the 1.6.x branch after the 1.6.1 release again. TLDR; it's just for record keeping.

**Comment by jezdez** [comment]
Alright, [1.6.1 is out](https://github.com/jazzband/django-push-notifications/pull/517) and I've merged the changes to the CI setup into master.

Closing this as fixed. The work to release the current master (2.0.0) can continue regularly and once a release (git tag) happens, Travis will push the files to the Jazzband site and ask @jleclanche and me to review it.
