### ISSUE TITLE
Investigate API keys for auto-deploy scripts

### ISSUE THREAD

**Issue by ncoghlan** [jazzband/roadies#156]
PyPI's API token support is now in beta, and could be of interest for Jazzband's release automation: https://discuss.python.org/t/pypi-security-work-multifactor-auth-progress-help-needed/1042/31?u=ncoghlan

Right now, every Jazzband project maintainer technically has access to the jazzband user's PyPI password (since we can run a trusted build on one of the repos we manage and get it to send us the decrypted password), rather than only the roadies having full access to that account.

If we want to switch to using a token for a particular project instead, I believe the steps required would be:

1. One of the roadies logs in to PyPI as the jazzband user, generates a new project scoped API token, and encrypts it with that repo's public Travis CI key
2. The project maintainer updates their Travis CI config to use the `@token` user (instead of `jazzband`) and the encrypted token instead of the encrypted password
3. The project maintainer makes a new release to confirm that everything is still working as intended

Alternatively, we could switch the release automation over to use API keys generated directly by project maintainers, and reserve the jazzband user's access to PyPI accounts for the cases where the Jazzband is providing continuity of maintenance for projects where the original maintainer has stepped away indefinitely without directly appointing a new maintainer.

**Comment by jezdez** [comment]
> PyPI's API token support is now in beta, and could be of interest for Jazzband's release automation: [discuss.python.org/t/pypi-security-work-multifactor-auth-progress-help-needed/1042/31?u=ncoghlan](https://discuss.python.org/t/pypi-security-work-multifactor-auth-progress-help-needed/1042/31?u=ncoghlan)

Absolutely, I've tracked the development and been looking forward to using it!

> Right now, every Jazzband project maintainer technically has access to the jazzband user's PyPI password (since we can run a trusted build on one of the repos we manage and get it to send us the decrypted password), rather than only the roadies having full access to that account.

That's not true anymore ever since the [project releases](https://jazzband.co/about/releases) have been implemented, in which releases happen against a per-project PyPI-style index on the Jazzband website (in case there are still Jazzband projects pointing to PyPI, they are misconfigured, e.g. contextlib2 😬). E.g. [pip-tools](https://github.com/jazzband/pip-tools/blob/520c7422c8cf33bb5260f54e8331bb132fdd889d/.travis.yml#L75-L90).

The credentials used for those are per-project and can be revoked by the roadies. Each file released to the Jazzband index will trigger a notification to the [project leads](https://jazzband.co/about/releases#security) (e.g. [pip-tools](https://jazzband.co/projects/pip-tools)) and ask them to review the files (and commit history that led to the release). Once reviewed they can with a press of a button on the Jazzband index release the file(s) to PyPI. 

Travis doesn't store the actual PyPI credential for the PyPI jazzband user at the moment but only the Jazzband index API key (per project).

> If we want to switch to using a token for a particular project instead, I believe the steps required would be:
> 
>     1. One of the roadies logs in to PyPI as the jazzband user, generates a new project scoped API token, and encrypts it with that repo's public Travis CI key
> 
>     2. The project maintainer updates their Travis CI config to use the `@token` user (instead of `jazzband`) and the encrypted token instead of the encrypted password
> 
>     3. The project maintainer makes a new release to confirm that everything is still working as intended
> 
> 
> Alternatively, we could switch the release automation over to use API keys generated directly by project maintainers, and reserve the jazzband user's access to PyPI accounts for the cases where the Jazzband is providing continuity of maintenance for projects where the original maintainer has stepped away indefinitely without directly appointing a new maintainer.

Given the current model of a staging area of releases so that project leads (~your "maintainers") can review them before they push them to PyPI, my plan was to simply switch to a per-PyPI-project API keys that will be used instead of the `jazzband` PyPI user.

I'm still trying to figure out if we can maybe automate the creation of the API key via PyPI's API somehow, but in doubt this would be a one-time process when transferring a repo/setting up releases.

**Comment by jezdez** [comment]
Also see #157.

**Comment by ncoghlan** [comment]
*cough* I guess that shows how long it has been since contextlib2's automation was set up, and how long it has been since I pushed a new release...

**Comment by jezdez** [comment]
No worries, I admit the biggest issues for Jazzband to thrive was the lack of announcements and release notes, which I hope to improve very soon by introducing an own discourse instance.

**Comment by jezdez** [comment]
Okay, so I've just added a API key for all projects until PyPI supports creating individual API keys via the API.

It's marginally safer than using the PyPI password for releases from the server before. I'm not sure if creating individual API keys for each Jazzband project would improve this further since if a leak would happen of one, then it's likely the others would leak, too. Closing for now..
