### ISSUE TITLE
Add project leads for contextlib2

### ISSUE THREAD

**Issue by jezdez** [jazzband/roadies#157]
This came up while triaging #156 

@ncoghlan Do you want to be added as project lead (currently strictly related to PyPI relases via the [Jazzband project release](https://jazzband.co/about/releases) system) and showe up on the project detail page on https://jazzband.co/projects/contextlib2? Anyone else who you would like to add?

**Comment by ncoghlan** [comment]
Yes please.

It's still just me at the moment.

**Comment by jezdez** [comment]
@ncoghlan Congrats on the first semi-automatic release! Please let me know if something is confusing or obviously needs a fix.

**Comment by ncoghlan** [comment]
@jezdez There was one glitch where I'm not sure whether my first attempt to publish the wheel file worked or not: the subsequent page showed the upload command output, but also showed the confirmation prompt again. Giving the confirmation a second time seemed to sort that out, though.

Otherwise it all seemed pretty clear, though!
