### ISSUE TITLE
bitbucket projects considered for inclusion?

### ISSUE THREAD

**Issue by chadgh** [jazzband/roadies#35]
I'm just wondering if projects hosted on bitbucket might be considered for inclusion down the road?

**Comment by jezdez** [comment]
That's difficult to say since I haven't fully researched if Bitbucket's API allows the same level of integration of the Jazzband code as GitHub's API does, e.g. to add users to an own team etc automatically. But that's just a matter of priority not a general disapproval of Bitbucket, so it may happen eventually.

**Comment by chadgh** [comment]
Thanks for the information. I think it would be great to have someday, but it isn't a huge deal.
