### ISSUE TITLE
Request for adding PyPI password to pip-tools

### ISSUE THREAD

**Issue by nvie** [jazzband/roadies#42]
Hello roadies! Can you add the encrypted jazzband PyPI account password to this project's `.travis.yml` file, please? Many thanks!

https://github.com/jazzband/pip-tools/blob/master/.travis.yml

**Comment by jezdez** [comment]
Yep, will do!

**Comment by davidovich** [comment]
@jezdez Hi, I would like to prepare 1.8.1rc1 of pip-tools, is the setup ready ? Thanks!

**Comment by jezdez** [comment]
Fixed in https://github.com/jazzband/pip-tools/compare/7cdb33ad0a583441a301ba6d0dee3b6f114a6cb5...2df97dad6e840e2b505e4c440610f1c30c837d46

Note, this changes the way the tox environments are integrated into Travis. It uses [tox-travis](http://tox-travis.readthedocs.io/) now which automatically maps the environments to Travis' Python versions. Also it only ever does the PyPI deploy if *all* other environments have passed.

**Comment by davidovich** [comment]
Excellent, thank you!

**Comment by nvie** [comment]
Thanks for driving this one together @jezdez and @davidovich! ❤️
