### ISSUE TITLE
Proposing django-form-utils

### ISSUE THREAD

**Issue by federicobond** [jazzband/roadies#73]
[django-form-utils](https://github.com/carljm/django-form-utils) contains some functionality that I found useful. I [reached out](https://github.com/carljm/django-form-utils/issues/18) to its maintainer to evaluate the possibility of migrating to Jazzband, since he is unable to continue maintaining it, and he would be fine with such a transition.

Let me know if this is a project you find valuable or if you think it duplicates the functionality of another.

**Comment by jezdez** [comment]
I think django-form-utils is a good match for Jazzband featurewise, but it sadly misses both automatic tests via Travis-CI and a documentation on Readthedocs.

I'm afraid that's a deal breaker since it'll simplify maintenance dramatically.

But if you're still interested, I'd like to encourage you to add those things, since there are docs in the README and a test setup based on tox already. Just needs some minor work to get it right.

**Comment by federicobond** [comment]
Hi @jezdez, thanks for responding. I have since convinced myself that it makes better sense to migrate to django-crispy-forms, which continues to be actively maintained.

**Comment by jezdez** [comment]
@federicobond Understood, thanks for the consideration though!
