### ISSUE TITLE
Setup PyPI releases for django-model-utils, publish 3.1.0

### ISSUE THREAD

**Issue by tony** [jazzband/roadies#79]
This is my first time setting up a release of a package.

https://github.com/jazzband/django-model-utils

https://github.com/jazzband/django-model-utils/tree/3.1.0

I don't think publishing packages is wired into the travis file yet.

**Comment by avelis** [comment]
@tony If you have write access to this repo you can update the travis.yml to at least attempt publishing upon making a release/tag. [There is an example of this at django-silk](https://github.com/jazzband/silk/blob/master/.travis.yml#L43). The only challenge then is making sure Jazzband is a member of the pypi org for the django-model-utils project.

**Comment by jezdez** [comment]
@avelis This won't be enough, I'll look into it @tony.

**Comment by pwhipp** [comment]
3.1.1 now

**Comment by pwhipp** [comment]
BTW:
```
$ pip show django_model_utils
Name: django-model-utils
Version: 3.1.1
Summary: Django model mixins and utilities
Home-page: https://github.com/jazzband/django-model-utils/
Author: JazzBand
Author-email: carl@oddbird.net
License: BSD
Location: /home/paul/.virtualenvs/sosadmin/src/django-model-utils
Requires: Django
```
BUT
```
$ pip install django-model-utils==3.1.1
Collecting django-model-utils==3.1.1
  Could not find a version that satisfies the requirement django-model-utils==3.1.1 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.6.0, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.2, 2.3, 2.3.1, 2.4, 2.5, 2.5.1, 2.5.2, 2.6, 2.6.1, 3.0.0)
No matching distribution found for django-model-utils==3.1.1
```

**Comment by jezdez** [comment]
So with Jazzband's new project member feature we can set up releases to occur automatically via Travis-CI but it requires one or more lead project members to confirm the release to PyPI first. The confirmation happens by receiving an email with instructions how to review the release for any release that is made via Travis-CI to the Jazzband project site. Once the release is confirmed it will be published to PyPI.

Per the [release guidelines](https://jazzband.co/about/releases) we need those lead project members to have made a non-trivial amount of contributions to the project to ensure that confirmation is based on experience with the project.

Since I only see @tony having made contributions in the past months since the move to Jazzband I'd like to ask @carljm again to be the lead project manager to confirm PyPI releases. Is that okay, @carljm?

**Comment by carljm** [comment]
Sure, I can give that a try and see how it goes.
