### ISSUE TITLE
Add encrypted password of PyPI jazzband to silk

### ISSUE THREAD

**Issue by albertyw** [jazzband/roadies#82]
[Jazzband silk](https://github.com/jazzband/silk) should be set up to autorelease, with its [.travis.yml](https://github.com/jazzband/silk/blob/master/.travis.yml#L53) configured.  The password for it seems to be misconfigured, leading to an error when releasing:

```
Fetching: dpl-1.8.43.gem (100%)
Successfully installed dpl-1.8.43
1 gem installed
invalid option "--password="
failed to deploy
```

Based on https://github.com/travis-ci/dpl/issues/327, I think the password in the `.travis.yml` is malformed and needs to be updated, similar to #69.

**Comment by avelis** [comment]
For the record, I added the encrypted password using now deprecated project setup guidelines which used `travis-cli` to add the jazzband user password to the yml config. I understand this is now no-longer the correct process anymore.

@jezdez I understand there is now a "lead" project member structure. Is that appropriate request I need to take in order to help continue a more regular release cycle for Django-Silk?

**Comment by albertyw** [comment]
@jezdez can we get some help on this?

**Comment by jezdez** [comment]
@albertyw @avelis Sorry for the delay, I'm setting it up now.

**Comment by jezdez** [comment]
Done in https://github.com/jazzband/silk/commit/c733b568b1fe8d6d69ca7d1d7b9700fc8ef58ecc.

@avelis I added you as project lead which means you'll get emails to confirm that Jazzband should publish a release to PyPI. Travis is now set up to push git tags automatically, so it should be self-service from now on. Please let me know if you have any questions.

@avelis Once a tag is pushed, you'll get a

**Comment by avelis** [comment]
@jezdez Thanks again for all you help on this.
